// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2e8wSRun_S6E89iP29zbbf5Kv8kVXLek',
    appId: '1:700368824359:web:107b105e455e559e310602',
    messagingSenderId: '700368824359',
    projectId: 'flutter-tic-tac-toe-94ef7',
    authDomain: 'flutter-tic-tac-toe-94ef7.firebaseapp.com',
    storageBucket: 'flutter-tic-tac-toe-94ef7.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh54cYMjjaxEbhHf2ewvvCkOYG4j0cyqI',
    appId: '1:700368824359:ios:56dbda37f6340407310602',
    messagingSenderId: '700368824359',
    projectId: 'flutter-tic-tac-toe-94ef7',
    storageBucket: 'flutter-tic-tac-toe-94ef7.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2e8wSRun_S6E89iP29zbbf5Kv8kVXLek',
    appId: '1:700368824359:web:20c1c2d3d3cf6fd2310602',
    messagingSenderId: '700368824359',
    projectId: 'flutter-tic-tac-toe-94ef7',
    authDomain: 'flutter-tic-tac-toe-94ef7.firebaseapp.com',
    storageBucket: 'flutter-tic-tac-toe-94ef7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh54cYMjjaxEbhHf2ewvvCkOYG4j0cyqI',
    appId: '1:700368824359:ios:56dbda37f6340407310602',
    messagingSenderId: '700368824359',
    projectId: 'flutter-tic-tac-toe-94ef7',
    storageBucket: 'flutter-tic-tac-toe-94ef7.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1udY5EaKEW7_HLFLgryPWhmDp4OA4lh8',
    appId: '1:700368824359:android:cfa3fb8cf189ad0b310602',
    messagingSenderId: '700368824359',
    projectId: 'flutter-tic-tac-toe-94ef7',
    storageBucket: 'flutter-tic-tac-toe-94ef7.firebasestorage.app',
  );

}